### ISSUE TITLE
How to make changes to Docker AIO Installation

### ISSUE THREAD

**Issue by BenIpinge** [openimis/openimis-dist_dkr#24]
How can I go about making changes on code on the all in one docker installation?

I tried file sharing but it creates a new container, meaning that changes only happen on the new container.

**Comment by delcroip** [comment]
you have to use volumes and replace the openIMIS folder (for the core) or create your own module and load it: either by using the conf https://github.com/openimis/openimis-dist_dkr/blob/386baa72d11e52d82c2c94dc04953aad78be3595/.env.example#L28

or by changing the BE context to use a local folder https://github.com/openimis/openimis-dist_dkr/blob/386baa72d11e52d82c2c94dc04953aad78be3595/docker-compose.yml#L34

br

**Comment by BenIpinge** [comment]
Can you please give an example of how to achieve that?
